bammmotif/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from .peng import views as peng_views
from .bamm import views as bamm_views
from .mmcompare import views as compare_views
from .database import views as db_views
from .bammscan import views as scan_views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('aboutBaMMmotif/', views.info, name='info'),
    path('documentation/', views.documentation, name='documentation'),
    path('links/', views.links, name='links'),
    path('contact/', views.contact, name='contact'),
    path('imprint/', views.imprint, name='imprint'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('job/submitted/', views.submitted, name='submitted'),

    # scan
    path('job/bamm_scan/', scan_views.run_bammscan_view, name='run_bamm_scan'),
    path('job/bamm_scan/<mode>/', scan_views.run_bammscan_view, name='run_bamm_scan'),
    path('job/bamm_scan/<mode>/<pk>/', scan_views.run_bammscan_view, name='run_bamm_scan'),
    path('scan_results/<uuid:pk>/', scan_views.result_details, name='scan_results'),

    # compare
    path('job/bamm_compare/', compare_views.run_compare_view, name='run_compare'),
    path('job/bamm_compare/<mode>)/', compare_views.run_compare_view, name='run_compare'),
    path('compare_results/<uuid:pk>/', compare_views.result_detail, name='run_compare'),

    # denovo
    path('job/seeding/', peng_views.run_peng_view, name='peng_predict'),
    path('job/seeding/<mode>/', peng_views.run_peng_view, name='peng_predict'),
    path('seed_results/<uuid:pk>/', peng_views.peng_results, name='peng_result_detail'),

    path('job/denovo/', bamm_views.one_step_denovo, name='one_step_denovo'),
    path('job/denovo/<mode>/', bamm_views.one_step_denovo, name='one_step_denovo'),
    path('denovo_results/<uuid:pk>/', bamm_views.denovo_results, name='denovo_results'),

    path('job/refinement/<uuid:pk>/', peng_views.run_refine, name='peng_to_bamm'),
    path('refine_results/<uuid:pk>/', peng_views.peng_to_bamm_result_detail, name='bamm_refinement'),

    # serve bed files for the genome browser
    path('bedtrack/<job_id>/<motif_no>/', views.serve_bed_file, name='serve_bed'),
    path('redirect_genome_browser/', views.run_genome_browser, name='run_genome_browser'),

    # database
    path('database/', db_views.maindb, name='maindb'),
    path('database/browse/<db_id>/', db_views.db_browse, name='db_browse'),
    path('database/<pk>/', db_views.db_detail, name='db_detail'),

    # find results
    path('my_results/', views.find_results, name='find_results'),
    path('my_results/csv/', views.serve_job_csv, name='download_job_list_csv'),
    path('find_result/<uuid:pk>/', views.find_results_by_id, name='find_results_by_id'),
    path('find_result/<uuid:pk>/status/', views.get_job_status, name='get_job_status'),
    path('peng_to_bamm_results/<uuid:pk>/', peng_views.peng_to_bamm_result_detail, name='peng_to_bamm_result_detail'),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bammmotif.urls')),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bammmotif/bamm/forms.py
from django import forms

from ..utils.ui import DBChoiceField, HELP_TEXTS

from .models import BaMMJob, OneStepBaMMJob


ONE_STEP_BASE_FIELDS = (
    'reverse_Complement', 'model_order',
    'extend', 'background_Order',
    'Background_Sequences', 'score_Seqset', 'score_Cutoff',
    'FDR',
    'MMcompare', 'motif_db', 'e_value_cutoff',
    'pattern_length', 'zscore_threshold', 'count_threshold',
    'objective_function', 'no_em', 'max_refined_motifs',
)


class _OneStepBammJobForm(forms.ModelForm):
    class Meta:
        model = OneStepBaMMJob
        fields = ('Input_Sequences',) + ONE_STEP_BASE_FIELDS


class OneStepBammJobForm(_OneStepBammJobForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['motif_db'] = DBChoiceField()
        for name, field in self.fields.items():
            field.help_text = HELP_TEXTS[name]


class _OneStepBammJobExampleForm(forms.ModelForm):
    class Meta:
        model = OneStepBaMMJob
        fields = ONE_STEP_BASE_FIELDS


class OneStepBammJobExampleForm(_OneStepBammJobExampleForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['motif_db'] = DBChoiceField()
        for name, field in self.fields.items():
            field.help_text = HELP_TEXTS[name]

bammmotif/database/forms.py
from django import forms

from ..utils.ui import DBChoiceField, HELP_TEXTS


class DBForm(forms.Form):
    search_term = forms.CharField(max_length=255, required=False,
                                  help_text=HELP_TEXTS['search_term'])
    database = DBChoiceField(help_text=HELP_TEXTS['motif_db'])

bammmotif/forms.py
from django import forms

from .models import JobInfo
from .models.validators import UUID_validator
from .utils.ui import HELP_TEXTS


class _MetaJobNameForm(forms.ModelForm):
    class Meta:
        model = JobInfo
        fields = ('job_name',)


class MetaJobNameForm(_MetaJobNameForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.help_text = HELP_TEXTS[name]


class FindForm(forms.Form):
    job_ID = forms.CharField(max_length=255, validators=[UUID_validator])


class _GenomeBrowserForm(forms.Form):
    organism = forms.CharField(max_length=255)
    assembly_id = forms.CharField(max_length=255)
    job_id = forms.CharField(max_length=255)
    motif_id = forms.IntegerField()


class GenomeBrowserForm(_GenomeBrowserForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.help_text = HELP_TEXTS[name]

bammmotif/mmcompare/forms.py
from django import forms
from .models import MMcompareJob
from ..utils.ui import DBChoiceField, HELP_TEXTS


class _MMCompareForm(forms.ModelForm):
    class Meta:
        model = MMcompareJob
        fields = ('Motif_InitFile', 'Motif_Init_File_Format',
                  'bgModel_File', 'e_value_cutoff', 'motif_db')


class MMCompareForm(_MMCompareForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.help_text = HELP_TEXTS[name]
        self.fields['motif_db'] = DBChoiceField(help_text=HELP_TEXTS['motif_db_compare'])


class _MMCompareExampleForm(forms.ModelForm):
    class Meta:
        model = MMcompareJob
        fields = ('e_value_cutoff', 'motif_db')


class MMCompareExampleForm(_MMCompareExampleForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.help_text = HELP_TEXTS[name]
        self.fields['motif_db'] = DBChoiceField(help_text=HELP_TEXTS['motif_db_compare'])

bammmotif/bamm/views.py
import itertools

from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.db import transaction

from ..forms import MetaJobNameForm, GenomeBrowserForm
from . import forms as bamm_forms

from ..utils import (
    get_result_folder,
    set_job_name_if_unset,
    check_fasta_input,
    register_job_session,
    get_user,
    upload_example_fasta,
)
from ..utils.meme_reader import check_low_seed_complexity

from ..views import redirect_if_not_ready
from .models import OneStepBaMMJob

from .tasks import denovo_pipeline


ONESTEP_JOBFORM = {
    'example': bamm_forms.OneStepBammJobExampleForm,
    'denovo': bamm_forms.OneStepBammJobForm
}


def one_step_denovo(request, mode='denovo'):
    max_file_size = settings.MAX_UPLOAD_FILE_SIZE
    if request.method == 'POST':
        metajob_form = MetaJobNameForm(request.POST)
        job_form = ONESTEP_JOBFORM[mode](request.POST, request.FILES)

        is_valid = metajob_form.is_valid() and job_form.is_valid()
        if is_valid:
            meta_job = metajob_form.save(commit=False)
            meta_job.user = get_user(request)
            meta_job.mode = "De-novo"
            meta_job.job_type = 'denovo'
            set_job_name_if_unset(meta_job)

            job = job_form.save(commit=False)
            job.meta_job = meta_job
            job_pk = meta_job.pk

            if mode == 'example':
                upload_example_fasta(job)
            else:
                is_valid = check_fasta_input(job, job_form, request.FILES)

            if is_valid:
                with transaction.atomic():
                    job.meta_job.save()
                    register_job_session(request, job.meta_job)
                    job.save()

                denovo_pipeline.delay(job_pk)

                return render(request, 'job/submitted.html', {
                    'pk': job_pk,
                    'result_target': 'denovo',
                })

    else:
        metajob_form = MetaJobNameForm()
        job_form = ONESTEP_JOBFORM[mode](initial={'max_refined_motifs': settings.DEFAULT_SEEDS_FOR_REFINEMENT})
        is_valid = True

    return render(request, 'denovo/one_step_denovo.html', {
        'metajob_form': metajob_form,
        'job_form': job_form,
        'max_file_size': max_file_size,
        'all_form_fields': itertools.chain(metajob_form, job_form),
        'mode': mode,
        'validation_errors': not is_valid,
        'max_seeds': settings.MAX_SEEDS_FOR_REFINEMENT,
    })


def denovo_results(request, pk):
    redirect_obj = redirect_if_not_ready(pk)
    if redirect_obj is not None:
        return redirect_obj

    result = get_object_or_404(OneStepBaMMJob, meta_job__pk=pk)
    motif_db = result.motif_db
    db_dir = motif_db.relative_db_model_dir

    warn_low_complexity = check_low_seed_complexity(result.meme_output)

    num_logos = range(1, (min(2, result.model_order)+1))
    return render(request, 'bamm/bamm_result_detail.html', {
        'result': result, 'opath': get_result_folder(pk),
        'mode': result.meta_job.mode,
        'Output_filename': result.filename_prefix,
        'num_logos': num_logos,
        'db_dir': db_dir,
        'low_complexity_warning': warn_low_complexity,
        'genome_browser_form': GenomeBrowserForm(),
    })

bammmotif/bammscan/views.py
from os import path
import itertools

from django.shortcuts import get_object_or_404, render
from django.db import transaction
from django.conf import settings


from ..models import ChIPseq
from ..forms import MetaJobNameForm, GenomeBrowserForm

from ..utils import (
    get_user,
    set_job_name_if_unset,
    get_result_folder,
    upload_example_fasta,
    upload_example_motif,
    register_job_session,
    check_motif_input,
    check_fasta_input,
)
from ..views import redirect_if_not_ready

from .forms import (
    BaMMScanExampleForm,
    BaMMScanDBForm,
    BaMMScanForm
)
from .models import BaMMScanJob
from .tasks import bamm_scan_pipeline
from .utils import upload_db_motif


def run_bammscan_view(request, mode='normal', pk='null'):
    if request.method == "POST":
        meta_job_form = MetaJobNameForm(request.POST)
        if mode == 'example':
            form = BaMMScanExampleForm(request.POST, request.FILES)
        elif mode == 'db':
            form = BaMMScanDBForm(request.POST, request.FILES)
            motif = get_object_or_404(ChIPseq, pk=pk)
        elif mode == 'normal':
            form = BaMMScanForm(request.POST, request.FILES)

        is_valid = form.is_valid() and meta_job_form.is_valid()
        if is_valid:
            meta_job = meta_job_form.save(commit=False)
            meta_job.user = get_user(request)
            meta_job.mode = "BaMMScan"
            meta_job.job_type = 'bammscan'
            set_job_name_if_unset(meta_job)
            meta_job.save()

            job = form.save(commit=False)
            job.meta_job = meta_job
            job_pk = meta_job.pk

            # if example is requested, load the sampleData
            if mode == 'example':
                upload_example_fasta(job)
                upload_example_motif(job)
            # enter db input
            elif mode == 'db':
                upload_db_motif(job, motif)
                is_valid = check_fasta_input(job, form, request.FILES) and is_valid
            else:
                is_valid = check_fasta_input(job, form, request.FILES) and is_valid
                is_valid = check_motif_input(job, form, request) and is_valid

            if is_valid:
                with transaction.atomic():
                    job.meta_job.save()
                    register_job_session(request, job.meta_job)
                    job.save()

                bamm_scan_pipeline.delay(job_pk)
                return render(request, 'job/submitted.html', {
                    'pk': job_pk,
                    'result_target': 'scan_results',
                })

    else:
        is_valid = True
        meta_job_form = MetaJobNameForm()
        if mode == 'example':
            form = BaMMScanExampleForm()
        elif mode == 'normal':
            form = BaMMScanForm()
        elif mode == 'db':
            form = BaMMScanDBForm()
            db_entry = get_object_or_404(ChIPseq, pk=pk)
            return render(request, 'bammscan/bammscan_input.html', {
                'job_form': form,
                'metajob_form': meta_job_form,
                'all_form_fields': itertools.chain(form, meta_job_form),
                'max_file_size': settings.MAX_UPLOAD_FILE_SIZE,
                'validation_errors': not is_valid,
                'mode': mode,
                'pk': pk,
                'db_entry': db_entry,
            })

    return render(request, 'bammscan/bammscan_input.html', {
        'job_form': form,
        'metajob_form': meta_job_form,
        'mode': mode,
        'all_form_fields': itertools.chain(form, meta_job_form),
        'max_file_size': settings.MAX_UPLOAD_FILE_SIZE,
        'validation_errors': not is_valid,
    })


def result_details(request, pk):
    redirect_obj = redirect_if_not_ready(pk)
    if redirect_obj is not None:
        return redirect_obj

    result = get_object_or_404(BaMMScanJob, pk=pk)
    meta_job = result.meta_job
    opath = get_result_folder(pk)
    filename_prefix = result.filename_prefix

    motif_db = result.motif_db
    db_dir = motif_db.relative_db_model_dir

    num_logos = range(1, (min(3, result.model_order+1)))
    return render(request, 'bammscan/result_detail.html', {
        'sequence_fname': path.basename(result.Input_Sequences.name),
        'motif_fname': path.basename(result.Motif_InitFile.name),
        'result': result,
        'opath': opath,
        'mode': meta_job.mode,
        'Output_filename': filename_prefix,
        'num_logos': num_logos,
        'db_dir': db_dir,
        'genome_browser_form': GenomeBrowserForm(),
    })

bammmotif/database/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)

from .forms import DBForm
from ..models import ChIPseq, MotifDatabase


def maindb(request):
    if request.method == "POST":
        form = DBForm(request.POST)
        if form.is_valid():
            motif_db = form.cleaned_data['database']

            if 'browse_button' in request.POST:
                return redirect('db_browse', db_id=motif_db.db_id)

            search_term = form.cleaned_data['search_term']
            if not search_term:
                form = DBForm(request.POST)
                return render(request, 'database/db_main.html', {'form': form, 'warning': True})
            db_entries = ChIPseq.objects.filter(target_name__icontains=search_term,
                                                motif_db=motif_db)
            if db_entries.exists():
                return render(
                    request, 'database/db_overview.html',
                    {
                        'protein_name': search_term,
                        'db_entries': db_entries,
                        'db_location': motif_db.relative_db_model_dir,
                        'is_bamm_database': motif_db.model_parameters.modelorder > 0,
                    })
            else:
                form = DBForm(request.POST)
                return render(request, 'database/db_main.html', {'form': form, 'warning': True})
    else:
        form = DBForm()
    return render(request, 'database/db_main.html', {'form': form})


def db_browse(request, db_id):
    motif_db = get_object_or_404(MotifDatabase, db_id=db_id)
    db_entries = ChIPseq.objects.filter(motif_db=db_id)
    search_term = motif_db.display_name

    return render(
        request, 'database/db_overview.html',
        {
            'protein_name': search_term,
            'db_entries': db_entries,
            'db_location': motif_db.relative_db_model_dir,
            'is_bamm_database': motif_db.model_parameters.modelorder > 0,
        })


def db_detail(request, pk):
    entry = get_object_or_404(ChIPseq, motif_id=pk)
    db_location = entry.motif_db.relative_db_model_dir
    return render(request, 'database/db_detail.html', {
        'entry': entry,
        'db_location': db_location,
        'is_bamm_database': entry.motif_db.model_parameters.modelorder > 0,
    })

bammmotif/templates/results/peng_results_main.html
{% extends "home/header.html" %}

{% block content %}



    <div class="jumbotron" style="background-color:white"><font color="black">
        <h2> Find your Job </h2>
        <hr style="border: 1px solid #1f2e2e">
        <form method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                <label for="id_job_ID"><font size=3>Enter Job ID: </label> <font color="#1f2e2e">
                <input id="id_job_ID" maxlength="455" name="job_ID" type="text" placeholder="i.e: fdd1d833-7192-4f20-8832-4857db4ddfb4 " required /></font> &nbsp
                <button type="submit" class="btn btn-primary btn-sm"  style="border:0px; background-color:#1f2e2e"><font color="white" size=3> Search Results </font></button>
            </p>
        </form>

        <br>
        <!-- <p>Or <a class="btn btn-primary btn-lg" href="{% url 'login' %}?next={{'/results/result_overview/'}}" role="button" style="border:0px; background-color:#1f2e2e"><font color="white">login </font></a> to view all your Jobs </p> -->

    </font>
    </div>



{% endblock %}

bammmotif/templates/results/peng_to_bamm_result_main.html
{% extends "home/header.html" %}

{% block content %}



    <div class="jumbotron" style="background-color:white"><font color="black">
        <h2> Find your Job </h2>
        <hr style="border: 1px solid #1f2e2e">
        {% if warning %}
            <p> <font color="#B22222">No Job found with the provided Job ID, did you enter the correct Job ID ? </font></p>
        {% endif %}
        <form method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                <label for="id_job_ID"><font size=3>Enter Job ID: </label> <font color="#1f2e2e">
                <input id="id_job_ID" maxlength="455" name="job_ID" type="text" placeholder="i.e: fdd1d833-7192-4f20-8832-4857db4ddfb4 " required /></font> &nbsp
                <button type="submit" class="btn btn-primary btn-sm"  style="border:0px; background-color:#1f2e2e"><font color="white" size=3> Search Results </font></button>
            </p>
        </form>

        <br>
        <!-- <p>Or <a class="btn btn-primary btn-lg" href="{% url 'login' %}?next={{'/results/result_overview/'}}" role="button" style="border:0px; background-color:#1f2e2e"><font color="white">login </font></a> to view all your Jobs </p> -->

    </font>
    </div>



{% endblock %}

bammmotif/templates/results/peng_to_bamm_result_overview.html
{% extends "home/header.html" %}

{% block content %}
    {% load static %}

    <div class="jumbotron" style="background-color:white"><font color="black">
        <h2> BaMMmotif Results from User: {{user.username}} </h2>
        <hr style="border: 1px solid #1f2e2e">
        <div>
            <table class="table table-hover">
                <tr>
                    <th> Submitted on  </th>
                    <th> Job Name        </th>
                    <th> Input Sequence File </th>
                    <th> Status        </th>
                    <th>                </th>
                </tr>
                {% for user_job in user_jobs %}
                    <tr>
                        <td> {{ user_job.created_at }} </td>
                        <td> {{ user_job.job_name }}     </td>
                        <td> {{ user_job.Inputseq_filename }} </td>
                        <td> <a href="{% url 'peng_to_bamm_result_detail' user_job.job_ID %}" role="button">{{user_job.status}}</a></td>
                        <td> <a href="{% url 'delete' user_job.job_ID %}" role="button"><span class="glyphicon glyphicon-trash" aria-hidden="true" style="color:black"></span></a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

bammmotif/templates/results/result_overview.html
{% extends "home/header.html" %}

{% block content %}
{% load static %}

<div class="jumbotron" style="background-color:white"><font color="black">
    <h2> BaMMmotif results from user: {{user.username}} </h2>
    <hr style="border: 1px solid #1f2e2e">   
    <div>
        <table class="table table-hover">
        <tr>
            <th> Submitted on  </th>
            <th> Job name        </th>
            <th> Input sequence file </th>
            <th> Status        </th>
            <th>                </th>
        </tr>
        {% for user_job in user_jobs %}
        <tr>
            <td> {{ user_job.created_at }} </td>
            <td> {{ user_job.job_name }}     </td>
            <td> {{ user_job.Inputseq_filename }} </td>
            <td> <a href="{% url 'result_detail' user_job.job_ID %}" role="button">{{user_job.status}}</a></td>
            <td> <a href="{% url 'delete' user_job.job_ID %}" role="button"><span class="glyphicon glyphicon-trash" aria-hidden="true" style="color:black"></span></a></td>
        </tr>
       {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

bammmotif/templates/results/result_status.html
{% extends "home/header.html" %}

{% block content %}
{% load static %}

{% if status == 'Error' or status  == 'No motifs found' or status == 'Killed' %}
<!-- no refreshing please -->
{%else %}
<meta http-equiv="refresh" content="5" >
{% endif %}

<div class="jumbotron"  style="background-color:white"><font color="black">
  <h2>
     {% if status == 'Error' %}
     We're sorry, your job has crashed...
     {% elif status == 'No motifs found' %}
     The seeding stage did not find any motifs...
     {% elif status == 'Killed' %}
     Your job took too long and was killed...
     {% else %}
     Your job {{job_name}} is still running...
     {% endif %}
  </h2>
     <hr class="header_line">

     {% if status == 'Error' or status == 'Killed' %}
     <div class="alert alert-warning">
       <p>
         We are very sorry for the crash. The admins of the server have already been notified.
       </p>
       <p>
         You are very welcome to contact us directly and we will try to resolve the problem as fast as possible.
         Please find the contact information <a href="{% url 'links' %}">here</a>.
      </p>
       <p>
        When reporting a bug, please add <strong>[{{job_id}}]</strong> to the report to help us speed up the trouble shooting.
      </p>
     </div>
     {% endif %}

     <div id="{{job_id}}">
        <p> Your job status: {{status}} </p>
        <p> You can watch the progress in the window below. </p>
        <!--<p> If you have submitted this job while being logged in, you will receive an email when it is finished. </p> -->

        <div style="background-color:black"><font color="white">
            <pre>{{ output }}</pre>
        </front>
        </div>
    </div>
  </font>
</div>

{% endblock %}

bammmotif/templates/results/results_main.html
ß
{% extends "home/header.html" %}
{% load tz %}

{% block content %}



<div class="jumbotron bamm_box"><font color="black">
  <h2> Find my job </h2>
  <p class="bamm_text">
      <hr class="header_line">

      {% if warning %}
      <div class="alert alert-warning">
        No job found with the provided job ID, did you enter a full job id?
      </div>
      {% endif %}

     <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            <label for="id_job_ID">Enter job ID: </label>
            <input id="id_job_ID" maxlength="100" size="46" name="job_ID" type="text" placeholder="i.e: 00000000-0000-0000-0000-000000000000" required /> &nbsp
            <button type="submit" class="btn btn-primary btn-sm run_button">Find job</button>
        </p>
    </form>
 </p>
</div>

<div class="jumbotron bamm_box"><font color="black">
  <h2>
    <span class="glyphicon glyphicon-info-sign" onmouseover="nhpup.popup($('#joblist_info').html(),{'width':400});" aria-hidden="true"></span>
    Jobs recently submitted by you
  </h2>
  <hr class="header_line"/>

  <div class="subheader_toolbar">
    <form action="{% url 'download_job_list_csv' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <button type="submit" class="btn btn-default">
        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
        Download as CSV
      </button>
    </form>
</div>

  <span>
  <table class="table table-hover bamm_text">
	<tr>
		<th>Submission time</th>
		<th>Job name</th>
		<th>Job type</th>
		<th>Job status</th>
		<th>Link</th>
	</tr>
	{% for session in jobs|dictsortreversed:"job.created_at"|slice:"20" %}
	<tr>
		<td>
			{{ session.job.created_at|localtime }}
		</td>
		<td>{{ session.job.job_name }}</td>
		<td>{{ session.job.job_type_display }}</td>
		<td>{{ session.job.status }}</td>
		<td>
			<a href="{% url 'find_results_by_id' session.job_id %}">
                                    <button type="submit" class="btn btn-default" aria-label="Go to" >
                                        <span class="glyphicon glyphicon-share-alt" aria-hidden="true"> </span>
                                    </button>
                        </a>
		</td>
	  </tr>
	  {%endfor %}
  </table>
</div>

<div class="modal fade" id="joblist_info" tabindex="-1" role="dialog" aria-labelledby="{{field.html_name}}_info">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <font color="#0B0719">
                    <p align="justify">
                      Jobs listed here were submitted from your current browser session.
                      <strong>Other users will not be able to see your jobs</strong> unless they know the full job id.
                      If you change computers, browsers or clear temporary data the list will be empty again.
                    </p>
                    <p align="justify">
                      <strong>For important jobs please also save the job id</strong> to make sure you will have access in the future.
                      The job id can be found in the settings drop-down menu on the result page or in the job list csv file which can be downloaded below.
                    </p>
                </font>
            </div>
        </div>
    </div>
</div>

{% endblock %}