bammmotif/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from .peng import views as peng_views
from .bamm import views as bamm_views
from .mmcompare import views as compare_views
from .database import views as db_views
from .bammscan import views as scan_views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('aboutBaMMmotif/', views.info, name='info'),
    path('documentation/', views.documentation, name='documentation'),
    path('links/', views.links, name='links'),
    path('contact/', views.contact, name='contact'),
    path('imprint/', views.imprint, name='imprint'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('job/submitted/', views.submitted, name='submitted'),

    # scan
    path('job/bamm_scan/', scan_views.run_bammscan_view, name='run_bamm_scan'),
    path('job/bamm_scan/<mode>/', scan_views.run_bammscan_view, name='run_bamm_scan'),
    path('job/bamm_scan/<mode>/<pk>/', scan_views.run_bammscan_view, name='run_bamm_scan'),
    path('scan_results/<uuid:pk>/', scan_views.result_details, name='scan_results'),

    # compare
    path('job/bamm_compare/', compare_views.run_compare_view, name='run_compare'),
    path('job/bamm_compare/<mode>)/', compare_views.run_compare_view, name='run_compare'),
    path('compare_results/<uuid:pk>/', compare_views.result_detail, name='run_compare'),

    # denovo
    path('job/seeding/', peng_views.run_peng_view, name='peng_predict'),
    path('job/seeding/<mode>/', peng_views.run_peng_view, name='peng_predict'),
    path('seed_results/<uuid:pk>/', peng_views.peng_results, name='peng_result_detail'),

    path('job/denovo/', bamm_views.one_step_denovo, name='one_step_denovo'),
    path('job/denovo/<mode>/', bamm_views.one_step_denovo, name='one_step_denovo'),
    path('denovo_results/<uuid:pk>/', bamm_views.denovo_results, name='denovo_results'),

    path('job/refinement/<uuid:pk>/', peng_views.run_refine, name='peng_to_bamm'),
    path('refine_results/<uuid:pk>/', peng_views.peng_to_bamm_result_detail, name='bamm_refinement'),

    # serve bed files for the genome browser
    path('bedtrack/<job_id>/<motif_no>/', views.serve_bed_file, name='serve_bed'),
    path('redirect_genome_browser/', views.run_genome_browser, name='run_genome_browser'),

    # database
    path('database/', db_views.maindb, name='maindb'),
    path('database/browse/<db_id>/', db_views.db_browse, name='db_browse'),
    path('database/<pk>/', db_views.db_detail, name='db_detail'),

    # find results
    path('my_results/', views.find_results, name='find_results'),
    path('my_results/csv/', views.serve_job_csv, name='download_job_list_csv'),
    path('find_result/<uuid:pk>/', views.find_results_by_id, name='find_results_by_id'),
    path('find_result/<uuid:pk>/status/', views.get_job_status, name='get_job_status'),
    path('peng_to_bamm_results/<uuid:pk>/', peng_views.peng_to_bamm_result_detail, name='peng_to_bamm_result_detail'),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bammmotif.urls')),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bammmotif/bamm/models.py
from os import path

from django.db import models
from django.db.models.signals import post_delete
from django.conf import settings
from django.dispatch import receiver

from ..models import (
    JobInfo,
    MotifDatabase,
    PengJob,
)
from ..utils import job_dir_storage as job_fs
from ..utils import (
    job_upload_to_input,
    file_size_validator,
    get_job_output_folder,
)
from ..peng.cmd_modules import ShootPengModule


FORMAT_CHOICES = (
    ('MEME', 'MEME'),
    ('BaMM', 'BaMM'),
)

INIT_CHOICES = (
    ('CustomFile', 'CustomFile'),
    ('PEnGmotif', 'PEnGmotif'),
    ('DBFile', 'DBFile'),
)


class BaMMJob(models.Model):
    meta_job = models.OneToOneField(JobInfo, on_delete=models.CASCADE, editable=False,
                                    primary_key=True)
    peng_job = models.ForeignKey(PengJob, editable=False, on_delete=models.CASCADE)
    num_motifs = models.IntegerField(default=1)

    # files
    Input_Sequences = models.FileField(upload_to=job_upload_to_input, storage=job_fs,
                                       null=True, validators=[file_size_validator])
    Background_Sequences = models.FileField(upload_to=job_upload_to_input, storage=job_fs,
                                            null=True, blank=True, validators=[file_size_validator])
    Motif_Initialization = models.CharField(max_length=255, choices=INIT_CHOICES,
                                            default="PEnGmotif")
    Motif_InitFile = models.FileField(upload_to=job_upload_to_input, storage=job_fs,
                                      null=True, blank=True, validators=[file_size_validator])
    Motif_Init_File_Format = models.CharField(max_length=255, choices=FORMAT_CHOICES,
                                              default="MEME")
    num_init_motifs = models.IntegerField(default=10)

    # options
    model_order = models.PositiveSmallIntegerField(default=2)
    reverse_Complement = models.BooleanField(default=True)
    extend = models.PositiveSmallIntegerField(default=0)

    # fdr options
    FDR = models.BooleanField(default=True)
    m_Fold = models.IntegerField(default=1)
    sampling_Order = models.PositiveSmallIntegerField(default=2)

    # EM options
    EM = models.BooleanField(default=True)
    q_value = models.DecimalField(default=0.9, max_digits=3, decimal_places=2)

    # scoring options
    score_Seqset = models.BooleanField(default=True)
    score_Cutoff = models.FloatField(default=0.0001)
    bgModel_File = models.FileField(upload_to=job_upload_to_input, storage=job_fs,
                                    null=True, blank=True, validators=[file_size_validator])

    # advanced options
    background_Order = models.PositiveSmallIntegerField(default=2)
    verbose = models.BooleanField(default=True)

    # MMcompare
    MMcompare = models.BooleanField(default=True)
    e_value_cutoff = models.DecimalField(default=0.5, max_digits=3, decimal_places=2)
    motif_db = models.ForeignKey(MotifDatabase, null=True, on_delete=models.CASCADE)

    has_bedfile = models.BooleanField(default=False)

    @property
    def filename_prefix(self):
        file_name = path.basename(self.Input_Sequences.name)
        prefix, _ = path.splitext(file_name)
        return prefix

    def input_basename(self):
        return path.basename(self.Input_Sequences.name)

    @property
    def full_motif_file_path(self):
        return path.join(settings.JOB_DIR, str(self.Motif_InitFile))

    @property
    def bamm_init_file(self):
        return self.Motif_InitFile

    @property
    def meme_output(self):
        return path.join(get_job_output_folder(self.meta_job.pk), 'seeds.meme')

    @property
    def n_threads(self):
        return settings.N_PARALLEL_THREADS

    @property
    def cvFold(self):
        return settings.FDR_CV_FOLD

    @property
    def bgModel_File(self):
        return path.join(get_job_output_folder(self.meta_job.pk), self.filename_prefix + '.hbcp')

    def __str__(self):
        return str(self.meta_job.pk)


@receiver(post_delete, sender=BaMMJob)
def delete_job_info(sender, instance, *args, **kwargs):
    if instance.meta_job:
        instance.meta_job.delete()


class OneStepBaMMJob(models.Model):

    # general settings
    meta_job = models.OneToOneField(JobInfo, on_delete=models.CASCADE, editable=False,
                                    primary_key=True)

    # shared
    Input_Sequences = models.FileField(upload_to=job_upload_to_input, storage=job_fs,
                                       null=True, validators=[file_size_validator])
    Background_Sequences = models.FileField(upload_to=job_upload_to_input, storage=job_fs,
                                            null=True, blank=True, validators=[file_size_validator])
    num_motifs = models.IntegerField(default=1)
    reverse_Complement = models.BooleanField(default=True)
    background_Order = models.PositiveSmallIntegerField(default=2)

    # peng-motif seeding
    temp_dir = models.CharField(max_length=100, null=True,
                                default=ShootPengModule.defaults['temp_dir'])
    pattern_length = models.IntegerField(default=ShootPengModule.defaults['pattern_length'])
    zscore_threshold = models.FloatField(default=ShootPengModule.defaults['zscore_threshold'])
    count_threshold = models.IntegerField(default=ShootPengModule.defaults['count_threshold'])
    objective_function = models.CharField(
        choices=[(choice, choice) for choice in ShootPengModule.objective_functions],
        max_length=50, default=ShootPengModule.defaults['optimization_score'])
    enrich_pseudocount_factor = models.FloatField(
        default=ShootPengModule.defaults['enrich_pseudocount_factor'])
    no_em = models.BooleanField(default=ShootPengModule.defaults['no_em'])
    em_saturation_threshold = models.FloatField(
        default=ShootPengModule.defaults['em_saturation_threshold'])
    em_threshold = models.FloatField(default=ShootPengModule.defaults['em_threshold'])
    em_max_iterations = models.IntegerField(default=ShootPengModule.defaults['em_max_iterations'])
    no_merging = models.BooleanField(default=ShootPengModule.defaults['no_merging'])
    bit_factor_threshold = models.FloatField(
        default=ShootPengModule.defaults['bit_factor_threshold'])
    use_default_pwm = models.BooleanField(default=ShootPengModule.defaults['use_default_pwm'])
    pwm_pseudo_counts = models.IntegerField(default=ShootPengModule.defaults['pwm_pseudo_counts'])
    silent = models.BooleanField(default=ShootPengModule.defaults['silent'])
    max_refined_motifs = models.IntegerField(default=3)

    # patches for shared attributes
    @property
    def fasta_file(self):
        return self.Input_Sequences

    @property
    def bg_sequences(self):
        return self.Background_Sequences

    @property
    def strand(self):
        return 'BOTH' if self.reverse_Complement else 'PLUS'

    @property
    def bg_model_order(self):
        return self.background_Order

    @property
    def cvFold(self):
        return settings.FDR_CV_FOLD

    @property
    def n_threads(self):
        return settings.N_PARALLEL_THREADS

    def input_basename(self):
        return path.basename(self.Input_Sequences.name)

    # BaMM related functionality

    # files
    Motif_Initialization = models.CharField(max_length=255, choices=INIT_CHOICES,
                                            default="PEnGmotif")
    Motif_InitFile = models.FileField(upload_to=job_upload_to_input, storage=job_fs,
                                      null=True, blank=True)
    Motif_Init_File_Format = models.CharField(max_length=255, choices=FORMAT_CHOICES, default="MEME")

    # options
    model_order = models.PositiveSmallIntegerField(default=2)
    extend = models.PositiveSmallIntegerField(default=0)

    # fdr options
    FDR = models.BooleanField(default=True)
    m_Fold = models.IntegerField(default=1)
    sampling_Order = models.PositiveSmallIntegerField(default=2)

    # EM options
    EM = models.BooleanField(default=True)

    # scoring options
    score_Seqset = models.BooleanField(default=True)
    score_Cutoff = models.FloatField(default=0.0001)
    bgModel_File = models.FileField(upload_to=job_upload_to_input, storage=job_fs,
                                    null=True, blank=True)

    # advanced options
    verbose = models.BooleanField(default=True)

    # MMcompare
    MMcompare = models.BooleanField(default=True)
    e_value_cutoff = models.DecimalField(default=0.5, max_digits=3, decimal_places=2)
    motif_db = models.ForeignKey(MotifDatabase, null=True, on_delete=models.CASCADE)

    has_bedfile = models.BooleanField(default=False)

    @property
    def filename_prefix(self):
        file_name = path.basename(self.Input_Sequences.name)
        prefix, _ = path.splitext(file_name)
        return prefix

    @property
    def full_motif_file_path(self):
        return path.join(settings.JOB_DIR, str(self.Motif_InitFile))

    @property
    def full_sequence_file_path(self):
        return path.join(settings.JOB_DIR, str(self.Input_Sequences.path))

    @property
    def meme_output(self):
        return path.join(get_job_output_folder(self.meta_job.pk), 'seeds.meme')

    @property
    def q_value(self):
        # for now set default p-value to 0.5
        return 0.5

    @property
    def bgModel_File(self):
        return path.join(get_job_output_folder(self.meta_job.pk), self.filename_prefix + '.hbcp')

    def __str__(self):
        return str(self.meta_job.pk)


@receiver(post_delete, sender=OneStepBaMMJob)
def delete_job_info(sender, instance, *args, **kwargs):
    if instance.meta_job:
        instance.meta_job.delete()

bammmotif/bamm/forms.py
from django import forms

from ..utils.ui import DBChoiceField, HELP_TEXTS

from .models import BaMMJob, OneStepBaMMJob


ONE_STEP_BASE_FIELDS = (
    'reverse_Complement', 'model_order',
    'extend', 'background_Order',
    'Background_Sequences', 'score_Seqset', 'score_Cutoff',
    'FDR',
    'MMcompare', 'motif_db', 'e_value_cutoff',
    'pattern_length', 'zscore_threshold', 'count_threshold',
    'objective_function', 'no_em', 'max_refined_motifs',
)


class _OneStepBammJobForm(forms.ModelForm):
    class Meta:
        model = OneStepBaMMJob
        fields = ('Input_Sequences',) + ONE_STEP_BASE_FIELDS


class OneStepBammJobForm(_OneStepBammJobForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['motif_db'] = DBChoiceField()
        for name, field in self.fields.items():
            field.help_text = HELP_TEXTS[name]


class _OneStepBammJobExampleForm(forms.ModelForm):
    class Meta:
        model = OneStepBaMMJob
        fields = ONE_STEP_BASE_FIELDS


class OneStepBammJobExampleForm(_OneStepBammJobExampleForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['motif_db'] = DBChoiceField()
        for name, field in self.fields.items():
            field.help_text = HELP_TEXTS[name]

bammmotif/bamm/views.py
import itertools

from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.db import transaction

from ..forms import MetaJobNameForm, GenomeBrowserForm
from . import forms as bamm_forms

from ..utils import (
    get_result_folder,
    set_job_name_if_unset,
    check_fasta_input,
    register_job_session,
    get_user,
    upload_example_fasta,
)
from ..utils.meme_reader import check_low_seed_complexity

from ..views import redirect_if_not_ready
from .models import OneStepBaMMJob

from .tasks import denovo_pipeline


ONESTEP_JOBFORM = {
    'example': bamm_forms.OneStepBammJobExampleForm,
    'denovo': bamm_forms.OneStepBammJobForm
}


def one_step_denovo(request, mode='denovo'):
    max_file_size = settings.MAX_UPLOAD_FILE_SIZE
    if request.method == 'POST':
        metajob_form = MetaJobNameForm(request.POST)
        job_form = ONESTEP_JOBFORM[mode](request.POST, request.FILES)

        is_valid = metajob_form.is_valid() and job_form.is_valid()
        if is_valid:
            meta_job = metajob_form.save(commit=False)
            meta_job.user = get_user(request)
            meta_job.mode = "De-novo"
            meta_job.job_type = 'denovo'
            set_job_name_if_unset(meta_job)

            job = job_form.save(commit=False)
            job.meta_job = meta_job
            job_pk = meta_job.pk

            if mode == 'example':
                upload_example_fasta(job)
            else:
                is_valid = check_fasta_input(job, job_form, request.FILES)

            if is_valid:
                with transaction.atomic():
                    job.meta_job.save()
                    register_job_session(request, job.meta_job)
                    job.save()

                denovo_pipeline.delay(job_pk)

                return render(request, 'job/submitted.html', {
                    'pk': job_pk,
                    'result_target': 'denovo',
                })

    else:
        metajob_form = MetaJobNameForm()
        job_form = ONESTEP_JOBFORM[mode](initial={'max_refined_motifs': settings.DEFAULT_SEEDS_FOR_REFINEMENT})
        is_valid = True

    return render(request, 'denovo/one_step_denovo.html', {
        'metajob_form': metajob_form,
        'job_form': job_form,
        'max_file_size': max_file_size,
        'all_form_fields': itertools.chain(metajob_form, job_form),
        'mode': mode,
        'validation_errors': not is_valid,
        'max_seeds': settings.MAX_SEEDS_FOR_REFINEMENT,
    })


def denovo_results(request, pk):
    redirect_obj = redirect_if_not_ready(pk)
    if redirect_obj is not None:
        return redirect_obj

    result = get_object_or_404(OneStepBaMMJob, meta_job__pk=pk)
    motif_db = result.motif_db
    db_dir = motif_db.relative_db_model_dir

    warn_low_complexity = check_low_seed_complexity(result.meme_output)

    num_logos = range(1, (min(2, result.model_order)+1))
    return render(request, 'bamm/bamm_result_detail.html', {
        'result': result, 'opath': get_result_folder(pk),
        'mode': result.meta_job.mode,
        'Output_filename': result.filename_prefix,
        'num_logos': num_logos,
        'db_dir': db_dir,
        'low_complexity_warning': warn_low_complexity,
        'genome_browser_form': GenomeBrowserForm(),
    })

bammmotif/templates/peng/peng_seeding.html
{% extends "home/header.html" %}

{% load widget_tweaks %}

{% block content %}

    <div class="container-fluid">

        <div class="jumbotron container-fluid" style="background-color:white"><font color="black">
            <h2>Find Seed PWMs</h2>
            <hr class="header_line">
            <div class='container-fluid'>

	    {% include 'utils/validation_error_box.html' %}

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <p>
                      <label for="{{ metajob_form.job_name.id_for_label }}">
                        <a class="testpup infopopup" onmouseover="nhpup.popup($('#{{ metajob_form.job_name.html_name }}_info').html(),{'width':400});" >
                            <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true"/>
                        </a>
                        {{ metajob_form.job_name.label }}:
                    </label>
                      <p class="indented">
                        {{ metajob_form.job_name|attr:"placeholder:i.e: My Job #1"}}
                      </p>
                    </p>

                    {% if mode == 'example' %}
                    <p>
                      <label for="{{job_form.fasta_file.id_for_label}}">
                        <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.fasta_file.html_name }}_info').html(),{'width':400});">
                          <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true"></span>
                        </a>
                        Input Sequences:
                      </label>
                    </p>
                    <p class="indented">
                      Example Data
                    </p>

                    {% else %}
                    <p>
                      <label for="{{ job_form.fasta_file.id_for_label }}">
                        <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.fasta_file.html_name }}_info').html(),{'width':400});">
                          <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true" />
                        </a>
                        Input Sequences:
                      </label>
                    </p>
                    <p class="advopt_input_font indented">
                      <input type="file" onchange="validate_file_size(this, {{ max_file_size }} )"
                             name="{{ job_form.fasta_file.html_name }}" id="{{ job_form.fasta_file.auto_id }}"/>
                    </p>

                    <p>
                      &emsp;
                      <a href="{% url 'peng_predict' mode="example" %}" role="button">
                        <span class="glyphicon glyphicon-play-circle example_button" aria-hidden="true">
                          Load example data
                        </span>
                      </a>
                    </p>
                    {% endif %}


                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true"
                         style="background-color:white"><font color="black">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOne" style="background-color:white"><font
                                    color="black">
                                <h2 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                                       aria-expanded="true" aria-controls="collapseOne"
                                       style="background-color:white"><font color="black">
                                        <h3><span class="glyphicon glyphicon-menu-down" aria-hidden="true"
                                                  style="color:black"></span> Advanced Options </h3>
                                    </a>
                                </h2>
                            </div>

                            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel"
                                 aria-labelledby="headingOne" style="background-color:white"><font color="black">
                                <div class="panel-body">



                                  <!-- general settings -->
                                  <p class="advanced_settings_header">
                                    <h3>General settings</h3>
                                    <hr />
                                  </p>

                                  <p class="indented">
                                    <label for="{{ job_form.reverse_Complement.id_for_label }}">
                                      <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.reverse_Complement.html_name }}_info').html(),{'width':400});" >
                                        <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true" />
                                      </a>
                                      Search on both strands:
                                    </label>
                                    <span class="advopt_input_font">
                                       &nbsp;&nbsp;  {{ job_form.reverse_Complement }}
                                    </span>
                                  </p>

                                  <p class="indented">
                                    <label for="{{ job_form.bg_sequences.id_for_label }}">
                                      <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.bg_sequences.html_name }}_info').html(),{'width':400});">
                                        <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true" />
                                      </a>
                                      Background Sequences:
                                    </label>
                                  </p>
                                  <p class="indented">
                                    <input type="file" onchange="validate_file_size(this, {{ max_file_size }} )"
                              name="{{ job_form.bg_sequences.html_name }}" id="{{ job_form.bg_sequences.auto_id }}"/>
                                  </p>

                                  <p class="indented">
                                    <label for="{{ job_form.bg_model_order.id_for_label }}">
                                      <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.bg_model_order.html_name }}_info').html(),{'width':400});">
                                        <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true" />
                                      </a>
                                      Background Model Order:
                                    </label>
                                    <span class="advopt_input_font">
                                      &nbsp;&nbsp; {{ job_form.bg_model_order|attr:"min:0"|attr:"max:2" }}
                                    </span>
                                </p>

                                  <!-- seeding settings -->
                                  <p class="advanced_settings_header">
                                    <h3>Seeding stage</h3>
                                    <hr />
                                  </p>

                                  <p class="indented">
                                    <label for="{{ job_form.pattern_length.id_for_label }}">
                                      <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.pattern_length.html_name }}_info').html(),{'width':400});">
                                        <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true"/>
                                      </a>
                                      Pattern Length:
                                    </label>
                                    <span class="advopt_input_font">
                                      &nbsp;&nbsp;
                                      <select id="id_pattern_length" type="number" name="pattern_length" required>
                                          <option value="4">4</option>
                                          <option value="6">6</option>
                                          <option value="8" selected>8</option>
                                          <option value="10">10</option>
                                      </select>
                                    </span>
                                  </p>

                                  <p class="indented">
                                    <label for="{{ job_form.zscore_threshold.id_for_label }}">
                                      <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.zscore_threshold.html_name }}_info').html(),{'width':400});">
                                        <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true" />
                                      </a>
                                      Z-Score Threshold:
                                    </label>
                                    <span class="advopt_input_font">
                                      &nbsp;&nbsp;
                                      <select id="id_zscore_threshold" type="number" name="zscore_threshold" required>
                                          <option value="2">2</option>
                                          <option value="5">5</option>
                                          <option value="10" selected="selected">10</option>
                                          <option value="20">20</option>
                                      </select>
                                    </span>
                                  </p>

                                  <p class="indented">
                                    <label for="{{ job_form.count_threshold.id_for_label }}">
                                      <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.count_threshold.html_name }}_info').html(),{'width':400});">
                                        <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true" />
                                      </a>
                                      Count Threshold:
                                    </label>
                                    <span class="advopt_input_font">
                                      &nbsp;&nbsp;{{ job_form.count_threshold|attr:"min:1"|attr:"max:25" }}
                                    </span>
                                  </p>

                                  <p class="indented">
                                    <label for={{ form.objective_function.id_for_label }}>
                                      <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.objective_function.html_name }}_info').html(),{'width':400});">
                                        <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true" />
                                      </a>
                                      IUPAC Optimization Score:
                                    </label>
                                    <span class="advopt_input_font">
                                      &nbsp;&nbsp; {{ job_form.objective_function }}
                                    </span>
                                  </p>

                                  <p class="indented">
                                    <label for="{{ job_form.no_em.id_for_label }}">
                                      <a class "testpup" onmouseover="nhpup.popup($('#{{ job_form.no_em.html_name }}_info').html(),{'width':400});">
                                        <span class="glyphicon glyphicon-info-sign info_icon" aria-hidden="true" />
                                      </a>
                                      Skip EM:
                                    </label>
                                    <span class="advopt_input_font">
                                      &nbsp;&nbsp; {{ job_form.no_em }}
                                    </span>
                                  </p>
                    <br>
            </div>
        </div>
    </div>

    <hr class="header_line">
    <p>
        <button class="btn btn-primary btn-lg run_button" type="submit">
            <font color="white">Find Seeds</font>
	      </button>
        &emsp;
        <a href="{% url 'find_results_by_id' pk='00000000-0000-0000-0000-000000000000' %}" role="button">
          <span class="glyphicon glyphicon-play-circle example_button" aria-hidden="true">
            View example result
          </span>
        </a>
        &emsp;
        <a href="{% url 'one_step_denovo' %}"  role="button">
          <span class="glyphicon glyphicon-play-circle example_button" aria-hidden="true">
            Automatic seed selection
          </span>
        </a>
    </p>
    </form>

    </div>
    </div>

    {% for field in all_form_fields %}
    <div class="modal fade" id="{{ field.html_name }}_info" tabindex="-1" role="dialog" aria-labelledby="{{field.html_name}}_info">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <font color="#0B0719">
                        <p align="justify"> {{ field.help_text }}</p>
                    </font>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock %}